---
title: "Lactamase model example dynamics"
output: 
  html_document
---
R code used to generate Figure 5D

```{r, eval = F}
.vsc.attach()
setwd("R/patch_occupancy_sim")
```

```{r imports}
library(ggplot2)
library(khroma)

config = "rust_config.json"

source("utils.R")
```

```{r}
writeConfig <- function(
  path,
  desc,

  mortality = 1.5,
  mut_stdev = 5e-4,
  mut_uniform = 0.05,

  write_every = 10,
  rounds = 1000000,
  initial = 0.227
) {
  txt <- sprintf('{
  "description": "%s",
  "rounds": %i,
  "write_every": %i,
  "mortality": %s,
  "max_biomass": 4.85915,
  "mut_stdev": %s,
  "mut_uniform": %s,
  "mut_range": [
    0.0,
    0.836
  ],
  "seed": 93117,
  "initial": [
    %s
  ]
}', desc, rounds, write_every, mortality, mut_stdev, mut_uniform, initial)
  write(txt, file = path)
}
```

## 
```{r start}
result <- "results/lactamase_example.csv"
if (!file.exists(result)) {
  writeConfig(
    config,
    result,
    mortality = 0.9,
    mut_stdev = 0.01,
    mut_uniform = 0,
    write_every = 10,
    rounds = 10000,
    initial = 0.201013
  )
  command <- sprintf(
    r"[cargo run --release --bin lactamase --manifest-path rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}


points <- read.csv(result, comment.char = "#")
```




```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(subset(points, time < 10000), aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.201013, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  scale_y_continuous(limits = c(0, NA)) +
  theme_bw(base_size = 12) +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1.7, text = element_text(family = "sans")) 

plt1
```