---
title: "Example runs"
output: 
  html_document
---
R code used to generate Figure 5A and 5B

```{r, eval = F}
.vsc.attach()
setwd("R-QSS/niche_shadow_sim")
```

```{r imports}
library(ggplot2)
library(cowplot)
library(khroma)

config = "rust_config.json"

source("utils.R")
```

## Small kernel, visualizing initial decrease
```{r start}
desc <- "smallmut_0.001_allpoints"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225,
    mut_stdev = 0.001,
    mut_uniform = 0.0,
    write_every = 1,
    rounds = 50000,
    initial = 0.109
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}

points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated
# Cut timesteps to get a reasonable number of points while capturing the beginning
fewerpoints <- subset(points, time < 2000 | time %% 25 == 0)

every10sec <- subset(points, time %% 10 == 0)
```

```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(fewerpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "Siderophore investment α",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian( ylim = c(0, 0.11)) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  theme_bw(base_size = 14) +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```



```{r, fig.width = 6, fig.height = 6}
# Zoom in on initial packing

tol = khroma::color("iridescent")
fewerpoints <- subset(points, 900 <= time & time <= 6000)

plt1 <- ggplot(fewerpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = ) +
  labs(
    x = "Simulation time",
    y = "Siderophore investment α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian(xlim = c(1000,6000), ylim = c(0, 0.01)) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```



```{r}
# Calculate total siderophore production
production <- aggregate(alpha * pressure ~ time, data = every10sec, FUN = sum)
names(production) <- c("time", "total_sid")

ggplot(production, aes(x = time, y = total_sid)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total siderophore production"
  ) +
  theme_bw() +
  scale_y_log10() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))
```


```{r}
# Calculate total biomass
biomass <- aggregate(pressure ~ time, data = every10sec, FUN = sum)
names(biomass) <- c("time", "total")

ggplot(biomass, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total system biomass"
  ) +
  theme_bw() +
  scale_y_log10() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))
```


```{r}
# Calculate total occupancy
occupancy <- aggregate(frequency ~ time, data = every10sec, FUN = sum)
names(occupancy) <- c("time", "total")

ggplot(occupancy, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total patch occupancy"
  ) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))
```

```{r}
# Calculate number of strains
strainnr <- as.data.frame(table(every10sec$time))
names(strainnr) <- c("time", "total")
strainnr$time <- as.numeric(strainnr$time)

ggplot(strainnr, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Number of coexisting strains"
  ) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))
```

## Small kernel, running for a very long time

```{r start}
desc <- "smallmut_0.001_longest"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225,
    mut_stdev = 0.001,
    mut_uniform = 0.0,
    write_every = 100000,
    rounds = 100000000,
    initial = 0.109
    #initial = 0.211586
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}


points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated 
```

```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(points, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian( ylim = c(0, 0.11)) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```



```{r}
# Calculate total siderophore production
production <- aggregate(alpha * pressure ~ time, data = points, FUN = sum)
names(production) <- c("time", "total_sid")

plt2 <- ggplot(production, aes(x = time, y = total_sid)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total siderophore production"
  ) +
  theme_bw() +
  scale_y_log10() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))
plt2
```


```{r}
# Calculate total biomass
biomass <- aggregate(pressure ~ time, data = points, FUN = sum)
names(biomass) <- c("time", "total")

plt3 <- ggplot(biomass, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total system biomass"
  ) +
  theme_bw() +
  scale_y_log10() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt3
```

```{r}
# Calculate total occupancy
occupancy <- aggregate(frequency ~ time, data = points, FUN = sum)
names(occupancy) <- c("time", "total")

plt4 <- ggplot(occupancy, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Total patch occupancy"
  ) +
  theme_bw() +
  scale_y_log10() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt4
```


```{r}
# Calculate number of strains
strainnr <- as.data.frame(table(points$time))
names(strainnr) <- c("time", "total")
strainnr$time <- as.numeric(as.character(strainnr$time))

plt5 <- ggplot(strainnr, aes(x = time, y = total)) +
  geom_point(size = 0.01) +
  labs(
    x = "Simulation time",
    y = "Number of coexisting strains"
  ) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.7, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt5
```

```{r}
# Histogram of alpha
plt6 <- ggplot(subset(points, time > 0), aes(x = alpha, weight = pressure)) +
  geom_vline(xintercept=0.109, linetype = "dashed") +
  geom_histogram(aes(y = after_stat(count / sum(count))), binwidth=0.002) +
  theme_bw() +
  labs(
    x = "Siderophore investment α",
    y = "Fraction of total biomass across simulation"
  ) +
  coord_cartesian( xlim = c(0, 0.11))

plt6
```

Assemble SI figure
```{r}
plot_list <- list(plt1, plt2, plt3, plt4, plt5, plt6)

plot <- plot_grid( # cowplot
  plotlist = plot_list,
  ncol = 2,
  nrow = 3,
  align = "hv",
  labels = c("A", "B", "C", "D", "E", "F"),
  label_size = 12,
  label_fontface = "bold",
  label_fontfamily = "sans"
)

save_plot(
  filename = "results/smallmut_SI.png", 
  plot = plot,
  base_height = 10,
  base_width = 7, 
  dpi = 300,
)
```








## Comparison to finite sim

```{r start}
desc <- "infinite_comp_0.01"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225,
    mut_stdev = 0.01,
    mut_uniform = 0.0,
    write_every = 10,
    rounds = 1e6,
    initial = 0.109
    #initial = 0.211586
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}


points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated 
```

```{r, fig.width = 6, fig.height = 6}
pltpoints <- subset(points, time > 995000)

tol = khroma::color("iridescent")

plt1 <- ggplot(pltpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian( ylim = c(0, 0.11)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0))) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.85, 0.8)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```


## Calculate five-number statistics of distributions
```{r}
# Load points, remove burn-in
points <- subset(points, time > 100000)

# Compute values for each time point, then record five-number summaries
production <- aggregate(alpha * pressure ~ time, data = points, FUN = sum)
productions <- fivenum(production[,2])

biomass <- aggregate(pressure ~ time, data = points, FUN = sum)
biomasses <- fivenum(biomass[,2])

occupancy <- aggregate(frequency ~ time, data = points, FUN = sum)
occupancies <- fivenum(occupancy[,2])

stats <- list(
  "production" = productions,
  "biomass" = biomasses,
  "occupancy" = occupancies
)

# Density plot
w <- points$pressure / sum(points$pressure)

dens <- density(
  x = points$alpha, 
  weights = w, 
  from = 0, 
  to = 0.25,
  bw = 0.002
)

density <- data.frame(
    alpha = dens$x,
    density = dens$y
  )

saveRDS(stats, "comparison_stats.rda")
saveRDS(density, "comparison_density.rda")
```

## Higher kernel example


```{r start}
desc <- "smallmut_0.01"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225,
    mut_stdev = 0.01,
    mut_uniform = 0.0,
    write_every = 1,
    rounds = 50000,
    initial = 0.109
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}

points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated
# Cut timesteps to get a reasonable number of points while capturing the beginning
fewerpoints <- subset(points, time < 2000 | time %% 25 == 0)

every10sec <- subset(points, time %% 10 == 0)
```

```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(fewerpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "Siderophore investment α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian(xlim = c(0,10000), ylim = c(0, 0.11)) +
  #scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```


## Higher mu


```{r start}
desc <- "smallmut_0.01_highermu"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225 * 2,
    mut_stdev = 0.01,
    mut_uniform = 0.0,
    write_every = 1,
    rounds = 50000,
    initial = 0.109
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}

points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated
# Cut timesteps to get a reasonable number of points while capturing the beginning
fewerpoints <- subset(points, time < 2000 | time %% 25 == 0)

every10sec <- subset(points, time %% 10 == 0)
```

```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(fewerpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "Siderophore investment α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian(ylim = c(0, 0.11)) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```



## Lower mu


```{r start}
desc <- "smallmut_0.01_lowermu"
result <- paste0("results/", desc, ".json")
if (!file.exists(result)) {
  writeConfig(
    config,
    desc,
    mortality = 24.1225 / 2,
    mut_stdev = 0.01,
    mut_uniform = 0.0,
    write_every = 1,
    rounds = 50000,
    initial = 0.109
  )
  command <- sprintf(
    r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
    config, result
  )
  code <- system(command)
}

points <- read.csv(result, comment.char = "#")
points <- points[-1,] # Time zero gets duplicated
# Cut timesteps to get a reasonable number of points while capturing the beginning
fewerpoints <- subset(points, time < 2000 | time %% 25 == 0)

every10sec <- subset(points, time %% 10 == 0)
```

```{r, fig.width = 6, fig.height = 6}


tol = khroma::color("iridescent")

plt1 <- ggplot(fewerpoints, aes(x = time, y = alpha, color = frequency)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#555555") +
  geom_hline(yintercept = 0.109, linetype = "dashed", color = "#555555") +
  geom_point(size = 0.001, stroke = 0.5) +
  labs(
    x = "Simulation time",
    y = "Siderophore investment α of surviving strains",
    color = "Patch\noccupancy\n"
  ) +
  scale_color_gradientn(colors = tol(23)[10:23],
                        trans = "log",
                        limits = c(0.0001, 1),
                        breaks = c(0.0001, 0.001, 0.01, 0.1, 1),
                        labels = c("0.0001", 0.001, 0.01, 0.1, 1)) +

  coord_cartesian(ylim = c(0, 0.11)) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0))) +
  theme_bw() +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 0.7)) +
  theme(aspect.ratio = 1, text = element_text(family = "sans"))

plt1
```
