---
title: "Patch occupancy simulation, sweeping mu"
output: 
  html_document
---
R code used to generate Figure 

```{r, eval = F}
.vsc.attach()
setwd("R-QSS/niche_shadow_sim")
```

```{r imports}
library(ggplot2)
library(cowplot)
library(khroma)

config = "rust_config.json"

source("utils.R")
```


```{r start}
values <- seq(from = 0.2, to = 5, by = 0.4)

run_rust <- function(mu) {
  desc <- sprintf("mu_%s", signif(mu, 2))
  result <- paste0("results/", desc, ".json")
  if (!file.exists(result)) {
    writeConfig(
      config,
      desc,
      mortality = 24.1225 * mu,
      mut_stdev = 0.1,
      mut_uniform = 0.0,
      write_every = 10,
      rounds = 1e6,
      initial = 0.109
    )
    command <- sprintf(
      r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
      config, result
    )
    code <- system(command)
  }
  result
}

results <- Vectorize(run_rust)(values)
```

# Collect statistics
```{r}
productions <- vector("list", length(values))
biomasses <- vector("list", length(values))
occupancies <- vector("list", length(values))
densities <- vector("list", length(values))

for (i in seq_along(results)) {
  # Load points, remove burn-in
  points <- read.csv(results[[i]], comment.char = "#")
  points <- subset(points, time > 100000)

  # Compute values for each time point, then record five-number summaries
  production <- aggregate(alpha * pressure ~ time, data = points, FUN = sum)
  productions[[i]] <- fivenum(production[,2])

  biomass <- aggregate(pressure ~ time, data = points, FUN = sum)
  biomasses[[i]] <- fivenum(biomass[,2])

  occupancy <- aggregate(frequency ~ time, data = points, FUN = sum)
  occupancies[[i]] <- fivenum(occupancy[,2])

  # Density plot
  w <- points$pressure / sum(points$pressure)
  
  dens <- density(
    x = points$alpha, 
    weights = w, 
    from = 0, 
    to = 0.25,
    bw = 0.002
  )
  densities[[i]] <- data.frame(
    alpha = dens$x,
    density = dens$y,
    value = values[[i]]
  )
}
```



```{r}
df <- as.data.frame(do.call(rbind, productions))
ylab = "Total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = NULL,
    y = ylab
  ) +
  theme_bw()
```

```{r}
df <- as.data.frame(do.call(rbind, biomasses))
ylab = "Total biomass"
df$stdev <- values

plt2 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = NULL,
    y = ylab
  )+
  theme_bw()
```

```{r}
df <- as.data.frame(do.call(rbind, occupancies))
ylab = "Total patch occupancy"
df$stdev <- values

plt3 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  )+
  theme_bw()
```

```{r}
plot_grid(plt1,plt2,plt3, nrow = 3)
```

```{r}
df <- as.data.frame(do.call(rbind, densities))
df$isone <- df$value == 1

ggplot(df, aes(x = alpha, y = density, group = value, color = value, linewidth = isone)) +
  geom_line() +
  geom_vline(xintercept = 0.109, linetype = "dashed") +
  theme_bw() +
  scale_color_YlOrBr(reverse = F, range = c(0.4, 1)) +
  scale_linewidth_manual(values = c(0.5, 1.5)) +
  labs(
    x = "Siderophore investment α",
    y = "Biomass density",
    color = "μ/δ(0)"
  ) +
  coord_cartesian(xlim = c(0, 0.11)) +
  guides(linewidth = "none") +
  theme(
    aspect.ratio = 1,
    legend.position = "inside", 
    legend.position.inside = c(0.9, 0.8),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
    )
```



```{r}
# Make relative to alpha_hat production
corrected <- lapply(seq_along(productions), function(i) {
  points <- read.csv(results[[i]], comment.char = "#", nrows = 1)
  productions[[i]] / (points$alpha * points$pressure)
})

df <- as.data.frame(do.call(rbind, corrected))
ylab = "Relative total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  ) +
  theme_bw() +
  theme(aspect.ratio = 1)
plt1
```



```{r}
# main text figure
df <- as.data.frame(do.call(rbind, productions))
df <- df / (96.88921*0.109)   # Make relative to alpha_hat at equilibrium
ylab = "Total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  ) +
  theme_bw() +
  theme(aspect.ratio = 1)
plt1
```


## Same thing, lower sigma


```{r start}
values <- seq(from = 0.2, to = 5, by = 0.4)

run_rust <- function(mu) {
  desc <- sprintf("mu_%s", signif(mu, 2))
  result <- paste0("results/", desc, "stdev0.01.json")
  if (!file.exists(result)) {
    writeConfig(
      config,
      desc,
      mortality = 24.1225 * mu,
      mut_stdev = 0.01,
      mut_uniform = 0.0,
      write_every = 10,
      rounds = 1e6,
      initial = 0.109
    )
    command <- sprintf(
      r"[cargo run --release --bin siderophoreQSS --manifest-path ../../rust/Cargo.toml -- %s %s]",
      config, result
    )
    code <- system(command)
  }
  result
}

results <- Vectorize(run_rust)(values)
```

# Collect statistics
```{r}
productions <- vector("list", length(values))
biomasses <- vector("list", length(values))
occupancies <- vector("list", length(values))
densities <- vector("list", length(values))

for (i in seq_along(results)) {
  # Load points, remove burn-in
  points <- read.csv(results[[i]], comment.char = "#")
  points <- subset(points, time > 100000)

  # Compute values for each time point, then record five-number summaries
  production <- aggregate(alpha * pressure ~ time, data = points, FUN = sum)
  productions[[i]] <- fivenum(production[,2])

  biomass <- aggregate(pressure ~ time, data = points, FUN = sum)
  biomasses[[i]] <- fivenum(biomass[,2])

  occupancy <- aggregate(frequency ~ time, data = points, FUN = sum)
  occupancies[[i]] <- fivenum(occupancy[,2])

  # Density plot
  w <- points$pressure / sum(points$pressure)
  
  dens <- density(
    x = points$alpha, 
    weights = w, 
    from = 0, 
    to = 0.25,
    bw = 0.002
  )
  densities[[i]] <- data.frame(
    alpha = dens$x,
    density = dens$y,
    value = values[[i]]
  )
}
```



```{r}
df <- as.data.frame(do.call(rbind, productions))
ylab = "Total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = NULL,
    y = ylab
  ) +
  theme_bw()
```

```{r}
df <- as.data.frame(do.call(rbind, biomasses))
ylab = "Total biomass"
df$stdev <- values

plt2 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = NULL,
    y = ylab
  )+
  theme_bw()
```

```{r}
df <- as.data.frame(do.call(rbind, occupancies))
ylab = "Total patch occupancy"
df$stdev <- values

plt3 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  )+
  theme_bw()
```

```{r}
plot_grid(plt1,plt2,plt3, nrow = 3)
```

```{r}
df <- as.data.frame(do.call(rbind, densities))
df$value <- log10(df$value)

ggplot(df, aes(x = alpha, y = density, group = value, color = value)) +
  geom_line() +
  geom_vline(xintercept = 0.109, linetype = "dashed") +
  theme_bw() +
  scale_color_YlOrBr(reverse = F, range = c(0.4, 1)) +
  labs(
    x = "Siderophore investment α",
    y = "Biomass density",
    color = "μ/δ(0)"
  ) +
  coord_cartesian(xlim = c(0, 0.11)) +
  theme(
    aspect.ratio = 1,
    legend.position = "inside", 
    legend.position.inside = c(0.9, 0.8),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
    )
```



```{r}
# Make relative to alpha_hat production
corrected <- lapply(seq_along(productions), function(i) {
  points <- read.csv(results[[i]], comment.char = "#", nrows = 1)
  productions[[i]] / (points$alpha * points$pressure)
})

df <- as.data.frame(do.call(rbind, corrected))
ylab = "Relative total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  ) +
  theme_bw() +
  theme(aspect.ratio = 1)
plt1
```



```{r}
# main text figure

df <- as.data.frame(do.call(rbind, productions))
ylab = "Total siderophore production"
df$stdev <- values

plt1 <- ggplot(df, aes(x = stdev, ymin = V1, lower = V2, middle = V3, upper = V4, ymax = V5, group = stdev)) +
  geom_boxplot(stat = "identity") + 
  labs(
    x = "Mortality rate μ/δ(0)",
    y = ylab
  ) +
  theme_bw() +
  theme(aspect.ratio = 1)
plt1
```

